# Generated by Django 6.0.3 on 2026-03-10 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobilier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='type_user',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Propriétaire')], max_length=20),
        ),
    ]
